version: '2'
services:
  cryptochurch.cc.mariadb:
    container_name: cryptochurch.cc.mariadb
    image: 'cryptochurch.cc/mariadb:10.3'
    build: './mariadb/10.3'
    volumes:
      - 'cryptochurch-cc-mariadb_data:/bitnami'
    ports:
        - '3325:3325'
    environment:
      - MYSQL_DATABASE=bitnami_wordpress
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=password
        #      - MYSQL_MASTER_PORT_NUMBER=3310
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - mongonet


  cryptochurch.cc:
    container_name: cryptochurch.cc.wordpress
    image: 'bitnami/wordpress:5'
    build: '.'
    ports:
        - '4458:4458'
    volumes:
      - 'cryptochurch-cc-wordpress_data:/bitnami'
      - './php.ini:/opt/bitnami/php/lib/php.ini'
      - './Divi:/bitnami/wordpress/wp-content/themes/Divi'
      - './Extra:/bitnami/wordpress/wp-content/themes/Extra'
      - './bloom:/bitnami/wordpress/wp-content/plugins/bloom'
      - './monarch:/bitnami/wordpress/wp-content/plugins/monarch'
    depends_on:
      - cryptochurch.cc.mariadb
    environment:
      - WORDPRESS_DATABASE_USER=root
      - WORDPRESS_DATABASE_PASSWORD=password
      - MARIADB_HOST=cryptochurch.cc.mariadb
      - MARIADB_PORT_NUMBER=3325
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - VIRTUAL_HOST=cryptochurch.cc
      - LETSENCRYPT_HOST=cryptochurch.cc
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - mongonet


volumes:
  cryptochurch-cc-mariadb_data:
    driver: local
  cryptochurch-cc-wordpress_data:
    driver: local

networks:
  mongonet:
    external: true

