version: '2'
services:
  blog.mybull.dog.mariadb:
    container_name: blog.mybull.dog.mariadb
    image: 'blog.mybull.dog/mariadb:10.3'
    build: './mariadb/10.3'
    volumes:
      - 'blog-mybull-dog-mariadb_data:/bitnami'
    ports:
        - '3342:3342'
    environment:
      - MYSQL_DATABASE=bitnami_wordpress
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=password
        #      - MYSQL_MASTER_PORT_NUMBER=3310
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - mongonet


  blog.mybull.dog:
    container_name: blog.mybull.dog.wordpress
    image: 'bitnami/wordpress:5'
    build: '.'
    ports:
        - '3343:3343'
    volumes:
      - 'blog-mybull-dog-wordpress_data:/bitnami'
      - './php.ini:/opt/bitnami/php/lib/php.ini'
      - './Divi:/bitnami/wordpress/wp-content/themes/Divi'
      - './Extra:/bitnami/wordpress/wp-content/themes/Extra'
      - './bloom:/bitnami/wordpress/wp-content/plugins/bloom'
      - './monarch:/bitnami/wordpress/wp-content/plugins/monarch'
    depends_on:
      - mybull.dog.mariadb
    environment:
      - WORDPRESS_DATABASE_USER=root
      - WORDPRESS_DATABASE_PASSWORD=password
      - MARIADB_HOST=blog.mybull.dog.mariadb
      - MARIADB_PORT_NUMBER=3342
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - VIRTUAL_HOST=blog.mybull.dog
      - LETSENCRYPT_HOST=blog.mybull.dog
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - mongonet


volumes:
  blog-mybull-dog-mariadb_data:
    driver: local
  blog-mybull-dog-wordpress_data:
    driver: local

networks:
  mongonet:
    external: true

