version: '2'
services:
  infinitoes.mariadb:
    container_name: infinitoes.mariadb
    image: 'infinitoes.com/mariadb:10.3'
    build: './mariadb/10.3'
    volumes:
      - 'infinitoes-mariadb_data:/bitnami'
    ports:
        - '3801:3801'
    environment:
      - MYSQL_DATABASE=bitnami_wordpress
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=password
        #      - MYSQL_MASTER_PORT_NUMBER=3310
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - mongonet


  infinitoes.com:
    container_name: infinitoes.com.wordpress
    image: 'bitnami/wordpress:5'
    ports:
        - '3901:3901'
    volumes:
      - 'infinitoes-wordpress_data:/bitnami'
      - './php.ini:/opt/bitnami/php/lib/php.ini'
      - './bitnami/wordpress/wp-content:/bitnami/wordpress/wp-content'
    depends_on:
      - infinitoes.mariadb
    environment:
      - WORDPRESS_DATABASE_USER=root
      - WORDPRESS_DATABASE_PASSWORD=password
      - MARIADB_HOST=infinitoes.mariadb
      - MARIADB_PORT_NUMBER=3801
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - VIRTUAL_HOST=infinitoes.com
      - LETSENCRYPT_HOST=infinitoes.com
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - mongonet


volumes:
  infinitoes-mariadb_data:
    driver: local
  infinitoes-wordpress_data:
    driver: local

networks:
  mongonet:
    external: true

