version: '2'
services:
  apt.buy.mariadb:
    container_name: apt.buy.mariadb
    image: 'apt.buy.git.pull/mariadb:10.3'
    build: './mariadb/10.3'
    restart: always
    volumes:
      - 'apt-buy-cc-mariadb_data:/bitnami'
    ports:
        - '3802:3802'
    environment:
      - MYSQL_DATABASE=bitnami_wordpress
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=password
        #      - MYSQL_MASTER_PORT_NUMBER=3310
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - mongonet


  apt.buy.me:
    container_name: apt.buy.me.wordpress
    image: 'bitnami/wordpress:5'
    restart: always
    ports:
        - '3902:3902'
    volumes:
      - 'apt-buy-wordpress_data:/bitnami'
      - './php.ini:/opt/bitnami/php/lib/php.ini'
      - './bitnami/wordpress/wp-content:/bitnami/wordpress/wp-content'
    depends_on:
      - apt.buy.mariadb
    environment:
      - WORDPRESS_DATABASE_USER=root
      - WORDPRESS_DATABASE_PASSWORD=password
      - MARIADB_HOST=apt.buy.mariadb
      - MARIADB_PORT_NUMBER=3802
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - VIRTUAL_HOST=apt-buy.me
      - LETSENCRYPT_HOST=apt-buy.me
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - mongonet


volumes:
  apt-buy-cc-mariadb_data:
    driver: local
  apt-buy-wordpress_data:
    driver: local

networks:
  mongonet:
    external: true

