version: '2'
services:
  puppy.mariadb:
    container_name: puppy.mariadb
    image: 'puppy.git.pull/mariadb:10.3'
    build: './mariadb/10.3'
    volumes:
      - 'puppy-mariadb_data:/bitnami'
    ports:
        - '3800:3800'
    environment:
      - MYSQL_DATABASE=bitnami_wordpress
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=password
        #      - MYSQL_MASTER_PORT_NUMBER=3310
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - mongonet


  puppy.git-pull.cheap:
    container_name: puppy.git-pull.cheap.wordpress
    image: 'bitnami/wordpress:5'
    ports:
        - '3900:3900'
    volumes:
      - 'puppy-wordpress_data:/bitnami'
      - './php.ini:/opt/bitnami/php/lib/php.ini'
      - './bitnami:/bitnami'
    depends_on:
      - puppy.mariadb
    environment:
      - WORDPRESS_DATABASE_USER=root
      - WORDPRESS_DATABASE_PASSWORD=password
      - MARIADB_HOST=puppy.mariadb
      - MARIADB_PORT_NUMBER=3800
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - VIRTUAL_HOST=puppy.git-pull.cheap
      - LETSENCRYPT_HOST=puppy.git-pull.cheap
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - mongonet


volumes:
  puppy-mariadb_data:
    driver: local
  puppy-wordpress_data:
    driver: local

networks:
  mongonet:
    external: true

