version: '2'
services:
  this.gym.rocks.mariadb:
    container_name: this.gym.rocks.mariadb
    image: 'this.gym.frickin.rocks/mariadb:10.3'
    build: './mariadb/10.3'
    volumes:
      - 'this-gym-rocks-mariadb_data:/bitnami'
    ports:
        - '3311:3311'
    environment:
      - MYSQL_DATABASE=bitnami_wordpress
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=password
        #      - MYSQL_MASTER_PORT_NUMBER=3310
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - mongonet


  this.gym.frickin.rocks:
    container_name: this.gym.frickin.rocks.wordpress
    image: 'bitnami/wordpress:5'
    build: '.'
    ports:
        - '4444:4444'
    volumes:
      - 'this-gym-rocks-wordpress_data:/bitnami'
      - './php.ini:/opt/bitnami/php/lib/php.ini'
    depends_on:
      - this.gym.rocks.mariadb
    environment:
      - WORDPRESS_DATABASE_USER=root
      - WORDPRESS_DATABASE_PASSWORD=password
      - MARIADB_HOST=this.gym.rocks.mariadb
      - MARIADB_PORT_NUMBER=3311
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - VIRTUAL_HOST=this.gym.frickin.rocks
      - LETSENCRYPT_HOST=this.gym.frickin.rocks
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - mongonet


volumes:
  this-gym-rocks-mariadb_data:
    driver: local
  this-gym-rocks-wordpress_data:
    driver: local

networks:
  mongonet:
    external: true

