version: '2'
services:
  dad.rocks.mariadb:
    container_name: dad.rocks.mariadb
    image: 'dad.frickin.rocks/mariadb:10.3'
    build: './mariadb/10.3'
    volumes:
      - 'dad-rocks-mariadb_data:/bitnami'
    ports:
        - '3322:3322'
    environment:
      - MYSQL_DATABASE=bitnami_wordpress
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=password
        #      - MYSQL_MASTER_PORT_NUMBER=3310
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - mongonet


  dad.frickin.rocks:
    container_name: dad.frickin.rocks.wordpress
    image: 'bitnami/wordpress:5'
    build: '.'
    ports:
        - '4455:4455'
    volumes:
      - 'dad-rocks-wordpress_data:/bitnami'
      - './php.ini:/opt/bitnami/php/lib/php.ini'
      - './Divi:/bitnami/wordpress/wp-content/themes/Divi'
      - './Extra:/bitnami/wordpress/wp-content/themes/Extra'
      - './bloom:/bitnami/wordpress/wp-content/plugins/bloom'
      - './monarch:/bitnami/wordpress/wp-content/plugins/monarch'
    depends_on:
      - dad.rocks.mariadb
    environment:
      - WORDPRESS_DATABASE_USER=root
      - WORDPRESS_DATABASE_PASSWORD=password
      - MARIADB_HOST=dad.rocks.mariadb
      - MARIADB_PORT_NUMBER=3322
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - VIRTUAL_HOST=dad.frickin.rocks
      - LETSENCRYPT_HOST=dad.frickin.rocks
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - mongonet


volumes:
  dad-rocks-mariadb_data:
    driver: local
  dad-rocks-wordpress_data:
    driver: local

networks:
  mongonet:
    external: true

