version: '2'
services:
  divi.rocks.mariadb:
    container_name: divi.rocks.mariadb
    image: 'divi.frickin.rocks/mariadb:10.3'
    build: './mariadb/10.3'
    volumes:
      - 'divi-rocks-mariadb_data:/bitnami'
    ports:
        - '3314:3314'
    environment:
      - MYSQL_DATABASE=bitnami_wordpress
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=password
        #      - MYSQL_MASTER_PORT_NUMBER=3310
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - mongonet


  divi.frickin.rocks:
    container_name: divi.frickin.rocks.wordpress
    image: 'bitnami/wordpress:5'
    build: '.'
    ports:
        - '4447:4447'
    volumes:
      - 'divi-rocks-wordpress_data:/bitnami'
      - './php.ini:/opt/bitnami/php/lib/php.ini'
      - './Divi:/bitnami/wordpress/wp-content/themes'
      - './Extra:/bitnami/wordpress/wp-content/themes'
    depends_on:
      - divi.rocks.mariadb
    environment:
      - WORDPRESS_DATABASE_USER=root
      - WORDPRESS_DATABASE_PASSWORD=password
      - MARIADB_HOST=divi.rocks.mariadb
      - MARIADB_PORT_NUMBER=3314
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - VIRTUAL_HOST=divi.frickin.rocks
      - LETSENCRYPT_HOST=divi.frickin.rocks
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - mongonet


volumes:
  divi-rocks-mariadb_data:
    driver: local
  divi-rocks-wordpress_data:
    driver: local

networks:
  mongonet:
    external: true

