version: '2'
services:
  rocks.mariadb:
    container_name: rocks.mariadb
    image: 'frickin.rocks/mariadb:10.3'
    build: './mariadb/10.3'
    volumes:
      - 'rocks-mariadb_data:/bitnami'
    ports:
        - '3315:3315'
    environment:
      - MYSQL_DATABASE=bitnami_wordpress
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=password
        #      - MYSQL_MASTER_PORT_NUMBER=3310
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - mongonet


  frickin.rocks:
    container_name: frickin.rocks.wordpress
    image: 'bitnami/wordpress:5'
    ports:
        - '4448:4448'
    volumes:
      - 'rocks-wordpress_data:/bitnami'
      - './php.ini:/opt/bitnami/php/lib/php.ini'
      - './Divi:/bitnami/wordpress/wp-content/themes/Divi'
      - './Extra:/bitnami/wordpress/wp-content/themes/Extra'
      - './bloom:/bitnami/wordpress/wp-content/plugins/bloom'
      - './monarch:/bitnami/wordpress/wp-content/plugins/monarch'
    depends_on:
      - rocks.mariadb
    environment:
      - WORDPRESS_DATABASE_USER=root
      - WORDPRESS_DATABASE_PASSWORD=password
      - MARIADB_HOST=rocks.mariadb
      - MARIADB_PORT_NUMBER=3315
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - VIRTUAL_HOST=frickin.rocks
      - LETSENCRYPT_HOST=frickin.rocks
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - mongonet


volumes:
  rocks-mariadb_data:
    driver: local
  rocks-wordpress_data:
    driver: local

networks:
  mongonet:
    external: true

