version: '2'
services:
  mybull.dog.mariadb:
    container_name: mybull.dog.mariadb
    image: 'mybull.dog.git.pull/mariadb:10.3'
    build: './mariadb/10.3'
    restart: always
    volumes:
      - 'mybull-dog-cc-mariadb_data:/bitnami'
    ports:
        - '3340:3340'
    environment:
      - MYSQL_DATABASE=bitnami_wordpress
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=password
        #      - MYSQL_MASTER_PORT_NUMBER=3310
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - mongonet


  mybull.dog:
    container_name: mybull.dog.wordpress
    image: 'bitnami/wordpress:5'
    restart: always
    ports:
        - '3341:3341'
    volumes:
      - 'mybull-dog-wordpress_data:/bitnami'
      - './php.ini:/opt/bitnami/php/lib/php.ini'
      - './bitnami/wordpress/wp-content:/bitnami/wordpress/wp-content'
    depends_on:
      - mybull.dog.mariadb
    environment:
      - WORDPRESS_DATABASE_USER=root
      - WORDPRESS_DATABASE_PASSWORD=password
      - MARIADB_HOST=mybull.dog.mariadb
      - MARIADB_PORT_NUMBER=3340
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - VIRTUAL_HOST=mybull.dog
      - LETSENCRYPT_HOST=mybull.dog
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - mongonet


volumes:
  mybull-dog-cc-mariadb_data:
    driver: local
  mybull-dog-wordpress_data:
    driver: local

networks:
  mongonet:
    external: true

