version: '2'
services:
  mom.rocks.mariadb:
    container_name: mom.rocks.mariadb
    image: 'mom.frickin.rocks/mariadb:10.3'
    build: './mariadb/10.3'
    volumes:
      - 'mom-rocks-mariadb_data:/bitnami'
    ports:
        - '3320:3320'
    environment:
      - MYSQL_DATABASE=bitnami_wordpress
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=password
        #      - MYSQL_MASTER_PORT_NUMBER=3310
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - mongonet


  mom.frickin.rocks:
    container_name: mom.frickin.rocks.wordpress
    image: 'bitnami/wordpress:5'
    build: '.'
    ports:
        - '4449:4449'
    volumes:
      - 'mom-rocks-wordpress_data:/bitnami'
      - './php.ini:/opt/bitnami/php/lib/php.ini'
      - './Divi:/bitnami/wordpress/wp-content/themes/Divi'
      - './Extra:/bitnami/wordpress/wp-content/themes/Extra'
      - './bloom:/bitnami/wordpress/wp-content/plugins/bloom'
      - './monarch:/bitnami/wordpress/wp-content/plugins/monarch'
    depends_on:
      - mom.rocks.mariadb
    environment:
      - WORDPRESS_DATABASE_USER=root
      - WORDPRESS_DATABASE_PASSWORD=password
      - MARIADB_HOST=mom.rocks.mariadb
      - MARIADB_PORT_NUMBER=3320
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - VIRTUAL_HOST=mom.frickin.rocks
      - LETSENCRYPT_HOST=mom.frickin.rocks
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - mongonet


volumes:
  mom-rocks-mariadb_data:
    driver: local
  mom-rocks-wordpress_data:
    driver: local

networks:
  mongonet:
    external: true

